language: python
python:
  - 2.6
  - 2.7
  - 3.3
install: |
  pip install --allow-all-external 'argparse>=1.2.1' coverage docutils pep8 python-coveralls six sphinx
  if python -c "from sys import *; exit(version_info < (3,))"
  then
    pip install unittest2py3k
  else
    pip install line_profiler unittest2
  fi
script: |
  if python -c "from sys import *; exit(version_info < (3,))"
  then
    coverage run --branch --module --source=argf unittest2 discover
  else
    scons check
  fi
after_success: coveralls
