language: c
addons:
 apt:
   packages:
   # Build.
   - cmake
   - make
   - gcc
   # Test.
   - python-pip
   - valgrind
install:
- export PATH=$HOME/.local/bin:$PATH
- pip install --user "`whoami`" cram
script:
- cmake .
- make
- cram -v test/
