language: python
python:
  - 2.6
  - 2.7
  - 3.3
install: |
  pip install --use-mirrors argparse coverage docutils python-coveralls semantic_version six
  if python -c "from sys import *; exit(version_info < (3,))"
  then
    pip install --use-mirrors unittest2py3k
  else
    pip install --use-mirrors pep8 unittest2
  fi
script: |
  if python -c "from sys import *; exit(version_info < (3,))"
  then
    coverage run --branch --module --source=argf unittest2 discover
  else
    scons check
  fi
after_success: coveralls
