language: c
addons:
 apt:
   packages:
   # Build.
   - cmake
   - make
   - gcc
   # Test.
   - python3-pip
   - valgrind
install:
- export PATH=$HOME/.local/bin:$PATH
- pip3 install --user cram
script:
- cmake .
- make
- cram -v test/
