version: '2'
services:
  devbox:
    image: docker.io/marciof/devbox
    network_mode: host
    build:
      context: .
      args:
        HOST_USER: ${USER}
    environment:
      DISPLAY:
      TERM:
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
    - ~:/mnt/home
  clion:
    entrypoint: clion/bin/clion.sh
    extends:
      service: devbox
    volumes:
    - ~/.clion-docker:/home/dev/.CLion2016.1
  idea:
    entrypoint: idea/bin/idea.sh
    extends:
      service: devbox
    volumes:
    - ~/.idea-docker:/home/dev/.IntelliJIdea2016.1
