version: '2'
services:
  clion:
    build: .
    image: docker.io/marciof/clion
    environment:
      DISPLAY:
      TERM:
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
    - ~:/mnt/home
    - ~/.clion-docker:/home/dev/.CLion2016.1
