version: '2'
services:
  clion:
    image: docker.io/marciof/clion
    network_mode: host
    build:
      context: .
      args:
        HOST_USER: ${USER}
    environment:
      DISPLAY:
      TERM:
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
    - ~:/mnt/home
    - ~/.clion-docker:/home/dev/.CLion2016.1
